name: testui3
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: none
environment:
  sdk: 3.9.2

dependencies:
  args: ^2.5.0
  consola: 0.1.0
  nocterm: 0.1.0
  hotreloader: ^4.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.0.0
  test: ^1.24.0
